### PR TITLE
Upgrade to PDK 2.5.0

### PR DESCRIPTION
**Pull request by Phil-Friderici**

### CODE REVIEW

**Review by anders-larsson — APPROVED** [review]
Looks good. Do you think we need to test these changes?

**Comment by Phil-Friderici** [comment]
These changes shouldn't touch the functionality. I guess a quick check would be more than enough.

**Comment by Phil-Friderici** [comment]
Released as v3.7.1

**Comment by anders-larsson** [comment]
BTW. I forgot, currently I've kept the changes we've made in this repository in branch `new_os_support`. Should we release versions of the forked module? How would it work once it's time move back?

**Comment by Phil-Friderici** [comment]
Well, sorry I wasn't aware of that. Actually I would rather use master/main branch for our changes. If we want to move back we have to rework anything we had changed since the fork. From my perspective it doesn't make a big difference if we keep all changes in a extra branch.

**Pull request merged**
